import Link from "next/link";
import { CalendarCheck, Download, ReceiptText, UsersRound } from "lucide-react";
import { normalizeFamilyFinanceParams } from "@/lib/family-finance-params";
import { allowedForecastYear, developerFeaturesEnabled } from "@/lib/developer-features";
import { getFamilyFinance } from "@/lib/family-finance";
import { familyPersonPositions, filterFamilyExpenses, getFamilyExpenseRange } from "@/lib/family-finance-filters";
import { buildExpensesHref, getMonthKey, addMonthsToMonthKey, type ExpenseFilterParams } from "@/lib/expense-filter-url";
import { buildCategoryRows, buildLabelRows, buildPeriodRows } from "@/lib/expense-analytics";
import { formatDate, formatMoney } from "@/lib/format";
import { getVisibleExpenses, getVisibleCategories, getExpenseLabels, getVisibleContracts, getVisibleDocumentRoots, getDocumentsForLinkedEntities } from "@/lib/queries";
import { toExpenseListItem, toExpenseDocumentItem, type ExpenseListItem } from "@/lib/expense-list";
import { ExpenseEntryList } from "./expense-entry-list";
import { ForecastChart } from "./expense-forecast-charts";
import { forecastReference, monthlyTotals, recordedMonths, smoothedForecast, withoutExcludedCategories } from "@/lib/expense-forecast";
import { FinanceAreaIndicator } from "./finance-area-switch";
import { FinanceToolbar } from "./finance-toolbar";
import { FinanceAnalysisRow } from "./finance-analysis-row";
import { FinanceTransitionMarker } from "./finance-transition-marker";
import { FamilyTransferAction } from "./family-transfer-action";
import { deleteFamilyTransfer } from "@/lib/family-finance-actions";
import { EmptyState, PageHeader } from "./ui";

type Position = { id: string; name: string; spending: number; sent: number; received: number; net: number };

export async function FamilyFinancePage({ params: rawParams, planning = false }: { params: ExpenseFilterParams; planning?: boolean }) {
  let params = normalizeFamilyFinanceParams(rawParams);
  const { session, expenses, categories, labels, transfers, members } = await getFamilyFinance();
  const currency = /^[A-Z]{3}$/.test(params.currency || "") ? params.currency! : "EUR";
  const selected = filterFamilyExpenses(expenses, params);
  const range = getFamilyExpenseRange(expenses, params);
  const analysisParams = { ...params, bereich: "familie", from: range.from.toISOString().slice(0, 10), to: range.to.toISOString().slice(0, 10) };
  const [own, ownCategories, ownLabels, contracts, roots, documents] = await Promise.all([
    getVisibleExpenses(session.family.id, session.user.id), getVisibleCategories(session.family.id, session.user.id, "EXPENSE"), getExpenseLabels(session.family.id, session.user.id), getVisibleContracts(session.family.id, session.user.id), getVisibleDocumentRoots(session.family.id, session.user.id, session.role), getDocumentsForLinkedEntities(session.family.id, session.user.id, "EXPENSE", selected.map(item => item.id))
  ]);
  const ownById = new Map(own.map(item => [item.id, toExpenseListItem(item)]));
  const list: ExpenseListItem[] = selected.map(item => ({ id: item.id, kind: "EXPENSE", date: item.date.toISOString(), amountCents: item.amountCents, currency: item.currency, description: item.description, store: item.store, paymentMethod: item.paymentMethod, categoryId: item.categoryId, labelId: item.labelId, category: item.category, label: item.label, personName: item.person.name, canEdit: item.canEdit, sharedWithFamily: true, editExpense: item.canEdit ? ownById.get(item.id) : undefined, contractId: null, fuelEntryId: null, recurringTransactionId: null, contract: null, fuelEntry: null, recurringTransaction: null, generatedByContract: false, generatedByFuelEntry: false, generatedByRecurringTransaction: false }));
  const docs: Record<string, ReturnType<typeof toExpenseDocumentItem>[]> = {};
  const rootsById = new Set(roots.map(root => root.id));
  for (const document of documents) if (document.linkedEntityId && (!document.documentRootId || rootsById.has(document.documentRootId))) (docs[document.linkedEntityId] ??= []).push(toExpenseDocumentItem(document));
  const total = selected.reduce((sum, item) => sum + item.amountCents, 0);
  const month = !params.year && !params.from && !params.to && /^\d{4}-(0[1-9]|1[0-2])$/.test(params.month || "") ? params.month! : (!params.year && !params.from && !params.to ? getMonthKey() : "");
  const view = params.view || "overview";
  const analysis = !["overview", "entries"].includes(view);
  const href = (next: ExpenseFilterParams = {}) => buildExpensesHref({ ...params, bereich: "familie" }, next);
  const money = (amount: number) => formatMoney(amount, currency);
  const filteredTransfers = transfers.filter(item => item.currency === currency && item.date >= range.from && item.date <= range.to);
  const rawPositions = familyPersonPositions(selected, filteredTransfers);
  const positions: Position[] = members.map(member => rawPositions.find(item => item.id === member.id) ?? { id: member.id, name: member.name, spending: 0, sent: 0, received: 0, net: 0 });
  const topPeople = [...positions].sort((a, b) => b.spending - a.spending || a.name.localeCompare(b.name, "de")).slice(0, 2);
  const showBudget = Boolean(month);
  const categoryRows = buildCategoryRows(selected, categories.filter(item => !item.archivedAt), total, showBudget);
  const labelRows = buildLabelRows(selected, labels);
  if (planning && !developerFeaturesEnabled(session)) params = { ...params, year: undefined };
  const forecastBase = expenses.filter(item => item.currency === currency && (!params.person || item.person.id === params.person));
  const forecastReferenceDate = forecastReference(forecastBase, allowedForecastYear(session, params.year));
  const forecastEntries = withoutExcludedCategories(forecastBase, categories);
  const forecast = smoothedForecast(forecastEntries, forecastReferenceDate.date);
  const forecastHistory = monthlyTotals(forecastEntries, forecastReferenceDate.date, 12);
  const exportQuery = new URLSearchParams(href().split("?")[1]);
  const entryList = (limit: number, totalCount: number) => <ExpenseEntryList initialEntries={list.slice(0, limit)} totalCount={totalCount} loadUrl={"/api/expenses/list?" + exportQuery.toString()} initialDocumentsByExpense={docs} categories={ownCategories} labels={ownLabels} contracts={contracts.map(item => ({ id: item.id, provider: item.provider, contractType: item.contractType }))} documentRoots={roots.map(item => ({ id: item.id, name: item.name }))} returnTo={href()} />;
  if (planning) {
    const months = recordedMonths(forecastEntries, forecastReferenceDate.date);
    const forecastOffset = forecastReferenceDate.selectedYear === null ? 1 : 0;
    const projected = forecast[forecastOffset]?.value ?? 0;
    const historyTotal = forecastHistory.reduce((sum, point) => sum + point.value, 0);
    const average = months ? Math.round(historyTotal / months) : 0;
    const forecastMonth = new Intl.DateTimeFormat("de-DE", { month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(`${forecast[forecastOffset]?.month ?? getMonthKey()}-01T00:00:00Z`));
    return <div className="forecast-page family-finance-page">
      <FinanceTransitionMarker view="planning" />
      <div className="task-page-head finance-page-head"><PageHeader title="Finanzen" suffix={<FinanceAreaIndicator />} /></div>
      <nav className="finance-primary-tabs" aria-label="Finanzbereich"><Link href={href({ view: "overview" })}>Übersicht</Link><Link href={href({ view: "categories" })}>Analyse</Link><Link className="active" href={href()}>Prognose</Link></nav>
      <section className="forecast-widget-section" aria-label={`Prognose für ${forecastMonth}`}>
        <div className="forecast-section-head"><h2>Prognose</h2><span>{forecastMonth}</span></div>
        <div className="finance-summary-panel forecast-widget-grid">
          <div className="finance-summary-metric forecast-widget tone-spending"><div className="finance-summary-card-head"><span>Ausgaben</span><i aria-hidden="true"><ReceiptText size={18} /></i></div><strong>{months ? money(projected) : "–"}</strong></div>
          <div className="finance-summary-metric forecast-widget tone-neutral"><div className="finance-summary-card-head"><span>Ø Monat</span><i aria-hidden="true"><CalendarCheck size={18} /></i></div><strong>{months ? money(average) : "–"}</strong></div>
          <div className="finance-summary-metric forecast-widget tone-neutral"><div className="finance-summary-card-head"><span>Datengrundlage</span><i aria-hidden="true"><UsersRound size={18} /></i></div><strong>{months ? `${months} Monate` : "–"}</strong></div>
        </div>
        <p className="muted">Trendprognose · nur geteilte Ausgaben · geglättet über 6 Monate</p>
      </section>
      {months < 6 ? <p className="forecast-note">{months === 0 ? "Noch keine abgeschlossenen Monate mit geteilten Ausgaben erfasst." : `Erst ${months} Monate erfasst · Prognose vorläufig`}</p> : null}
      <section className="panel forecast-tile"><div className="forecast-section-head"><h2>Verlauf</h2><span>12 Monate</span></div><ForecastChart showMonthlyValues={false} history={forecastHistory} forecast={forecast} spendingLabel="Geteilte Ausgaben" currency={currency} /></section>
    </div>;
  }
  return <div className="family-finance-page">
    <FinanceTransitionMarker view={view === "overview" ? "overview" : view === "entries" ? "entries" : "analysis"} />
    <div className="task-page-head finance-page-head"><PageHeader title="Finanzen" suffix={<FinanceAreaIndicator />} /><FinanceToolbar params={{ ...params, bereich: "familie" }} categories={categories} labels={labels} years={[]} currentMonthKey={getMonthKey()} paymentMethods={[]} resultCount={selected.length} activeFilterCount={[params.person, params.category, params.label, params.q].filter(Boolean).length} filterContent={<FilterForm params={params} view={view} month={month} categories={categories} labels={labels} people={members} />} /></div>
    <nav className="finance-primary-tabs"><Link className={!analysis ? "active" : ""} href={href({ view: "overview" })}>Übersicht</Link><Link className={analysis ? "active" : ""} href={href({ view: "categories" })}>Analyse</Link><Link href={"/ausgaben/planung?" + new URLSearchParams({ bereich: "familie", currency }).toString()}>Prognose</Link></nav>
    <section className="filter-system"><div className="period-navigator"><FamilyPeriodNavigator month={month} year={typeof params.year === "string" ? params.year : undefined} href={href} /></div><div className="overview-actions secondary-filter-actions expense-secondary-actions"><Link className="button secondary" href="/ausgaben/setup/serien?bereich=familie">Serien</Link><Link className="button secondary" href="/ausgaben/setup?bereich=familie">Setup</Link></div></section>
    {analysis ? <nav className="finance-analysis-subtabs">{[["categories", "Kategorien"], ["labels", "Labels"], ["budgets", "Budgets"], ["people", "Personen"], ["compare", "Vergleich"]].map(([key, label]) => <Link key={key} className={view === key ? "active" : ""} href={href({ view: key })}>{label}</Link>)}</nav> : <nav className="finance-analysis-subtabs"><Link className={view === "overview" ? "active" : ""} href={href({ view: "overview" })}>Überblick</Link><Link className={view === "entries" ? "active" : ""} href={href({ view: "entries" })}>Einträge</Link></nav>}
    {view === "overview" ? <section className="finance-overview-page spacing-top"><section className="finance-summary-panel"><Metric label="Gemeinsam ausgegeben" value={money(total)} detail="Geteilte Ausgaben im Zeitraum" icon={<ReceiptText size={17} />} />{topPeople.map(person => <Metric key={person.id} label={person.name} value={money(person.spending)} detail="Tatsächlich bezahlt" icon={<UsersRound size={17} />} />)}{topPeople.length < 2 ? <Metric label="Weiteres Mitglied" value="–" detail="Noch keine Ausgabe im Zeitraum" icon={<UsersRound size={17} />} /> : null}</section><Snapshot title="Ausgaben nach Kategorie" detail="Vorschau der wichtigsten Kategorien." href={href({ view: "categories" })}><FamilyBudgetPressureList rows={categoryRows} showBudget={showBudget} money={money} /></Snapshot><Snapshot title="Letzte Buchungen" detail={formatDate(range.from) + " bis " + formatDate(range.to)} href={href({ view: "entries" })}>{list.length ? entryList(10, Math.min(10, list.length)) : <EmptyState>Noch keine Buchungen im Zeitraum.</EmptyState>}</Snapshot><PeoplePanel positions={positions} money={money} href={href({ view: "people" })} /><TransferPanel transfers={filteredTransfers} currentUserId={session.user.id} money={money} /></section> : null}
    {analysis && view === "categories" ? <Analysis title="Kategorien">{categoryRows.filter(row => row.spending > 0).map(row => <FinanceAnalysisRow key={row.id ?? "unassigned"} row={row} dimension="category" params={analysisParams} returnParams={params} currency={currency} percent={row.percent} />)}</Analysis> : null}
    {analysis && view === "labels" ? <Analysis title="Familienlabels">{labelRows.filter(row => row.spending > 0).map(row => <FinanceAnalysisRow key={row.id ?? row.name} row={row} dimension="label" params={analysisParams} returnParams={params} currency={currency} percent={total ? row.spending / total * 100 : 0} />)}</Analysis> : null}
    {analysis && view === "budgets" ? <Analysis title="Budgets">{categoryRows.map(row => <Link key={row.id ?? "unassigned"} className="family-analysis-row" href={href({ category: row.id ?? "unassigned", view: "entries" })}><span>{row.name}</span><strong>{money(row.spending)}</strong></Link>)}</Analysis> : null}
    {analysis && view === "people" ? <Analysis title="Personen"><div className="section-head compact-section-head"><p className="muted">Netto getragen berücksichtigt Ausgleiche.</p><FamilyTransferAction /></div><PeopleRows positions={positions} money={money} /></Analysis> : null}
    {analysis && view === "compare" ? <Analysis title="Monatsvergleich">{buildPeriodRows(filterFamilyExpenses(expenses, { ...params, from: "1900-01-01", to: undefined, month: undefined, year: undefined }), categories, "month").map(row => <Link className="family-analysis-row" href={href({ month: row.label, view: "entries" })} key={row.label}><span>{row.label}</span><strong>{money(row.spending)}</strong></Link>)}</Analysis> : null}
    {view === "entries" ? <section className="panel expense-section"><div className="section-head compact-section-head"><div><h2 className="section-title">Einträge</h2><p className="muted">{formatDate(range.from) + " bis " + formatDate(range.to) + " · " + list.length + " Einträge"}</p></div><Link className="icon-button" aria-label="Excel exportieren" href={"/api/expenses/export?" + exportQuery.toString()}><Download size={19} /></Link></div>{list.length ? entryList(100, list.length) : <EmptyState>Noch keine Buchungen im Zeitraum.</EmptyState>}</section> : null}
  </div>;
}

function FilterForm({ params, view, month, categories, labels, people }: { params: ExpenseFilterParams; view: string; month: string; categories: { id: string; name: string }[]; labels: { id: string; name: string }[]; people: { id: string; name: string }[] }) { return <form action="/ausgaben" className="form form-grid finance-filter-form" id="finance-filter-form"><input type="hidden" name="bereich" value="familie" /><input type="hidden" name="view" value={view} /><label>Suche<input name="q" defaultValue={params.q ?? ""} /></label><label>Monat<input type="month" name="month" defaultValue={month} /></label><label>Von<input type="date" name="from" defaultValue={params.from ?? ""} /></label><label>Bis<input type="date" name="to" defaultValue={params.to ?? ""} /></label><label>Kategorie<select name="category" defaultValue={typeof params.category === "string" ? params.category : ""}><option value="">Alle</option>{categories.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Label<select name="label" defaultValue={typeof params.label === "string" ? params.label : ""}><option value="">Alle</option>{labels.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Person<select name="person" defaultValue={params.person ?? ""}><option value="">Alle</option>{people.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label></form>; }
function Metric({ label, value, detail, icon }: { label: string; value: string; detail: string; icon: React.ReactNode }) { return <div className="finance-summary-metric tone-spending"><div className="finance-summary-card-head"><span>{label}</span><i>{icon}</i></div><strong>{value}</strong><small>{detail}</small><div className="finance-summary-spark"><b style={{ width: "55%" }} /></div></div>; }
function Snapshot({ title, detail, href, children }: { title: string; detail: string; href: string; children: React.ReactNode }) { return <section className="panel finance-overview-snapshot"><div className="section-head compact-section-head"><div><h2 className="section-title">{title}</h2><p className="muted">{detail}</p></div><Link className="button secondary" href={href}>Alle</Link></div>{children}</section>; }
function PeopleRows({ positions, money }: { positions: Position[]; money: (value: number) => string }) { return <div className="family-person-list">{positions.map(item => <div className="family-analysis-row" key={item.id}><span><strong>{item.name}</strong><small className="muted">Ausgleich: {money(item.sent) + " gesendet · " + money(item.received) + " erhalten"}</small></span><span><small className="muted">Ausgaben</small><strong>{money(item.spending)}</strong></span><span><small className="muted">Netto getragen</small><strong>{money(item.net)}</strong></span></div>)}</div>; }
function PeoplePanel({ positions, money, href }: { positions: Position[]; money: (value: number) => string; href: string }) { return <Snapshot title="Ausgaben nach Personen" detail="Tatsächlich bezahlt und nach Ausgleichen." href={href}><PeopleRows positions={positions} money={money} /></Snapshot>; }
function TransferPanel({ transfers, currentUserId, money }: { transfers: Awaited<ReturnType<typeof getFamilyFinance>>["transfers"]; currentUserId: string; money: (value: number) => string }) { return <section className="panel finance-overview-snapshot"><div className="section-head compact-section-head"><div><h2 className="section-title">Ausgleich</h2><p className="muted">Echte Zahlungen verändern keine Ausgaben.</p></div><FamilyTransferAction /></div>{transfers.slice(0, 3).map(item => <div className="family-analysis-row" key={item.id}><span><strong>{item.sender.name + " → " + item.recipient.name}</strong><small className="muted">{formatDate(item.date) + (item.note ? " · " + item.note : "")}</small></span><strong>{money(item.amountCents)}</strong>{item.createdByUserId === currentUserId ? <form action={deleteFamilyTransfer}><input type="hidden" name="id" value={item.id} /><button className="icon-button" type="submit" aria-label="Ausgleich entfernen">×</button></form> : null}</div>)}{!transfers.length ? <p className="muted">Noch keine Ausgleiche im gewählten Zeitraum.</p> : null}</section>; }
function Analysis({ title, children }: { title: string; children: React.ReactNode }) { return <section className="panel finance-category-page spacing-top"><h2 className="section-title">{title}</h2>{children}</section>; }
function FamilyPeriodNavigator({ month, year, href }: { month: string; year?: string; href: (next: ExpenseFilterParams) => string }) { const isYear = Boolean(year); const currentMonth = month || getMonthKey(); const currentYear = Number((isYear ? year : currentMonth.slice(0, 4))); const title = isYear ? String(currentYear) : new Intl.DateTimeFormat("de-DE", { month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(currentMonth + "-01")); return <div className="period-nav-main"><Link className="period-nav-button" href={isYear ? href({ year: String(currentYear - 1), month: undefined }) : href({ month: addMonthsToMonthKey(currentMonth, -1), year: undefined })}>‹</Link><div className="period-nav-current"><span>{isYear ? "Jahresansicht" : "Monatsansicht"}</span><strong>{title}</strong></div><Link className="period-nav-button" href={isYear ? href({ year: String(currentYear + 1), month: undefined }) : href({ month: addMonthsToMonthKey(currentMonth, 1), year: undefined })}>›</Link><Link className="period-nav-button period-current-icon" href={href({ month: getMonthKey(), year: undefined })} aria-label="Aktuellen Monat anzeigen"><CalendarCheck size={18} /></Link><div className="period-mode-toggle"><Link className={!isYear ? "active" : ""} href={href({ month: currentMonth, year: undefined })}>Monat</Link><Link className={isYear ? "active" : ""} href={href({ year: String(currentYear), month: undefined })}>Jahr</Link></div></div>; }
function FamilyBudgetPressureList({ rows, showBudget, money }: { rows: ReturnType<typeof buildCategoryRows>; showBudget: boolean; money: (amount: number) => string }) { const visible = (showBudget ? [...rows].sort((a, b) => b.budgetUsage - a.budgetUsage || b.spending - a.spending) : rows.filter(row => row.spending > 0).sort((a, b) => b.spending - a.spending)).slice(0, 4); if (!visible.length) return <EmptyState>Noch keine Budgetdaten im Zeitraum.</EmptyState>; return <div className="finance-budget-list">{visible.map(row => <div className="finance-budget-row" key={row.name}><span className="finance-budget-icon" style={{ background: row.color }} aria-hidden="true">•</span><div><strong>{row.name}</strong><span>{showBudget ? row.budget > 0 ? row.budgetUsage.toFixed(0) + "% vom Budget genutzt" : "Ohne Budget" : row.percent.toFixed(0) + "% der Ausgaben"}</span><div className="bar-wrap budget-bar"><span style={{ width: Math.max(4, showBudget ? row.budgetUsage : row.percent) + "%", background: row.color }} /></div></div><div className="amount-column"><strong>{money(row.spending)}</strong></div></div>)}</div>; }
