import { CategoryIconPicker } from "./category-icon-picker";
import Link from "next/link";
import { db } from "@/lib/db";
import { requireFinanceMember } from "@/lib/family-finance";
import { saveFamilyTerm, saveFamilyMapping } from "@/lib/family-finance-actions";
import { FinanceAreaSwitch } from "./finance-area-switch";
import { EmptyState, PageHeader } from "./ui";
import { FinanceSetupEdit } from "./finance-setup-edit";
import { CategoryIcon } from "./category-icon";
import { exportFamilyFinanceToSynology } from "@/lib/family-finance-export";
import { budgetCadenceLabel } from "@/lib/expense-analytics";
import { ChevronRight, FileSpreadsheet, Link2, Repeat, Shapes, Tags } from "lucide-react";

export async function FamilyFinanceSetup({ section = "" }: { section?: string }) {
  const { family, user, role } = await requireFinanceMember();
  const familyId = family.id;
  const [categories, labels, personalCategories, personalLabels, categoryMaps, labelMaps, series] = await Promise.all([
    db.familyFinanceCategory.findMany({ where: { familyId }, orderBy: { name: "asc" } }),
    db.familyFinanceLabel.findMany({ where: { familyId }, orderBy: { name: "asc" } }),
    db.category.findMany({ where: { familyId, ownerUserId: user.id, type: "EXPENSE" }, orderBy: { name: "asc" } }),
    db.expenseLabel.findMany({ where: { familyId, ownerUserId: user.id }, orderBy: { name: "asc" } }),
    db.familyCategoryMapping.findMany({ where: { familyId, userId: user.id } }),
    db.familyLabelMapping.findMany({ where: { familyId, userId: user.id } }),
    db.recurringTransaction.findMany({ where: { familyId, sharedWithFamily: true, kind: "EXPENSE", deletedAt: null }, select: { id: true, status: true, startDate: true, ownerUserId: true, owner: { select: { name: true } } } })
  ]);
  const admin = role === "ADMIN";
  const sections = [["kategorien", "Kategorien", Shapes, "Gemeinsame Begriffe, Budgets und Prognose"], ["labels", "Labels", Tags, "Gemeinsame Projekte und Themen"], ["zuordnungen", "Meine Zuordnungen", Link2, "Eigene Begriffe der Familie zuordnen"], ["serien", "Serien", Repeat, "Geteilte wiederkehrende Ausgaben"], ["sicherung", "Excel-Auswertung", FileSpreadsheet, "Familienauswertung exportieren"]] as const;
  const sectionTitle = section === "kategorien" ? "Kategorien" : section === "labels" ? "Labels" : section === "zuordnungen" ? "Meine Zuordnungen" : section === "serien" ? "Serien" : section === "sicherung" ? "Excel-Auswertung" : "Finanz-Setup";
  return <div className="finance-setup-space family-finance-page">
    <nav className="desktop-section-nav family-desktop-setup-nav" aria-label="Familien-Finanz-Setup">
      <Link href="/ausgaben/setup?bereich=familie" className={!section ? "active" : ""} aria-current={!section ? "page" : undefined}>Übersicht</Link>
      {sections.map(([key, name]) => <Link href={`/ausgaben/setup/${key}?bereich=familie`} className={section === key ? "active" : ""} aria-current={section === key ? "page" : undefined} key={key}>{name}</Link>)}
    </nav>
    <header className="finance-setup-head"><Link className="finance-setup-back" href={section ? "/ausgaben/setup?bereich=familie" : "/ausgaben?bereich=familie"} aria-label="Zurück zu Finanzen">←</Link><PageHeader title={sectionTitle} /></header><FinanceAreaSwitch />
    {!section ? <><p className="muted">Gemeinsame Begriffe und Budgets verwalten oder persönliche Kategorien und Labels zuordnen. Nur ausdrücklich geteilte Ausgaben erscheinen bei der Familie.</p><nav className="finance-setup-nav">{sections.map(([key, name, Icon, description]) => <Link className="finance-setup-nav-row" href={`/ausgaben/setup/${key}?bereich=familie`} key={key}><span className={`finance-setup-nav-icon tone-${key}`}><Icon size={20}/></span><span><strong>{name}</strong><small>{description}</small></span><ChevronRight size={17}/></Link>)}</nav></> : null}
    {["kategorien","labels"].includes(section) ? <>
      <section className="setup-card setup-card-primary family-term-panel">
        <div className="setup-card-head"><div><h2 className="section-title">{section === "kategorien" ? "Familienkategorien" : "Familienlabels"}</h2><p className="muted">Gemeinsame Begriffe stehen allen Familienmitgliedern für geteilte Ausgaben zur Verfügung.</p></div></div>
        <div className={section === "kategorien" ? "category-editor-list" : "label-management-list"}>
          {(section === "kategorien" ? categories : labels).map(term => <div className="label-management-row category-management-row" key={term.id}>
            <div><strong>{"icon" in term ? <span className="category-icon-swatch" style={{ background: term.color }}><CategoryIcon icon={term.icon} size={16} /></span> : null}{term.name}</strong><span className="muted">{term.archivedAt ? "Archiviert" : "Aktiv"}{" · "}{("monthlyBudgetCents" in term ? term.monthlyBudgetCents : term.budgetCents) > 0 ? `Budget: ${(("monthlyBudgetCents" in term ? term.monthlyBudgetCents : term.budgetCents) / 100).toLocaleString("de-DE", { style: "currency", currency: "EUR" })} · ${budgetCadenceLabel(term.budgetCadence)}` : "Ohne Budget"}</span></div>
            {admin ? <div className="label-management-actions"><FinanceSetupEdit title={`${term.name} bearbeiten`}><form action={saveFamilyTerm} className="form form-grid compact"><input type="hidden" name="id" value={term.id} /><input type="hidden" name="type" value={section === "kategorien" ? "category" : "label"}/><label>Name<input name="name" defaultValue={term.name} required maxLength={100}/></label><label>Farbe<input type="color" name="color" defaultValue={term.color}/></label>{"icon" in term ? <CategoryIconPicker defaultValue={term.icon}/> : null}<label>Budgetbetrag in Euro<input name="budget" inputMode="decimal" defaultValue={(("monthlyBudgetCents" in term ? term.monthlyBudgetCents : term.budgetCents) / 100).toFixed(2)}/></label><label>Zeitraum<select name="budgetCadence" defaultValue={term.budgetCadence}>{section === "kategorien" ? <><option value="MONTHLY">Monatlich</option><option value="YEARLY">Jährlich</option></> : <><option value="MONTHLY">Monatlich</option><option value="YEARLY">Jährlich</option><option value="ALL_TIME">Allzeit</option></>}</select></label>{"excludeFromForecast" in term ? <label className="checkbox-field"><input type="checkbox" name="excludeFromForecast" defaultChecked={term.excludeFromForecast}/> Aus Gesamtprognose ausschließen</label> : null}<label className="checkbox-field"><input type="checkbox" name="archived" defaultChecked={Boolean(term.archivedAt)}/> Archiviert</label><button className="button full-span" type="submit">Speichern</button></form></FinanceSetupEdit></div> : null}
          </div>)}
          {!(section === "kategorien" ? categories : labels).length ? <EmptyState>Noch keine gemeinsamen {section === "kategorien" ? "Kategorien" : "Labels"} vorhanden.</EmptyState> : null}
        </div>
      </section>
      {admin ? <section className="setup-card family-term-create"><div className="setup-card-head"><div><h2 className="section-title">{section === "kategorien" ? "Neue Familienkategorie" : "Neues Familienlabel"}</h2></div></div><form className="form compact" action={saveFamilyTerm}><input type="hidden" name="type" value={section === "kategorien" ? "category" : "label"}/><label>Name<input name="name" required maxLength={100}/></label><label>Farbe<input name="color" type="color" defaultValue="#16776f"/></label>{section === "kategorien" ? <CategoryIconPicker /> : null}<label>Budgetbetrag in Euro<input name="budget" inputMode="decimal" /></label><label>Zeitraum<select name="budgetCadence" defaultValue={section === "kategorien" ? "MONTHLY" : "ALL_TIME"}>{section === "kategorien" ? <><option value="MONTHLY">Monatlich</option><option value="YEARLY">Jährlich</option></> : <><option value="MONTHLY">Monatlich</option><option value="YEARLY">Jährlich</option><option value="ALL_TIME">Allzeit</option></>}</select></label><button className="button secondary" type="submit">Anlegen</button></form></section> : null}
    </>:null}
    {section === "zuordnungen" ? <section className="setup-card family-mapping-panel"><p className="muted">Änderungen gelten auch für ältere geteilte Ausgaben. Eine Zuordnung allein veröffentlicht nichts.</p>{([ ["category",personalCategories,categories,categoryMaps], ["label",personalLabels,labels,labelMaps] ] as const).map(([type,personal,shared,mappings]) => <section className="family-mapping-group" key={type}><div className="finance-series-heading"><h2 className="section-title">{type === "category" ? "Kategorien" : "Labels"}</h2><span>{personal.length}</span></div><div className="label-management-list">{personal.map(p => <form action={saveFamilyMapping} key={p.id} className="label-management-row family-mapping-row"><input type="hidden" name="type" value={type}/><input type="hidden" name="personalId" value={p.id}/><label><strong>{p.name}</strong><select name="targetId" defaultValue={mappings.find(m => m.personalId === p.id)?.targetId ?? ""}><option value="">Nicht zugeordnet</option>{shared.map(t => <option key={t.id} value={t.id} disabled={Boolean(t.archivedAt) && mappings.find(m => m.personalId === p.id)?.targetId !== t.id}>{t.name}{t.archivedAt ? " · Archiviert" : ""}</option>)}<option value="__copy">„{p.name}“ gemeinsam übernehmen</option></select></label><button className="button secondary" type="submit">Zuordnen</button></form>)}</div></section>)}</section> : null}
    {section === "serien" ? <section className="setup-card family-series-panel"><div className="finance-series-heading"><h2 className="section-title">Geteilte Ausgabenserien</h2><span>{series.length}</span></div><div className="category-editor-list">{series.length ? series.map(s => <div className="finance-series-row" key={s.id}><div className="finance-series-summary"><span className="finance-series-copy"><strong>{s.owner.name}</strong><small>{s.status === "ACTIVE" ? "Aktiv" : "Pausiert"} · Geteilte Ausgabenserie</small></span></div>{s.ownerUserId === user.id ? <Link className="finance-setup-icon" href="/ausgaben/setup/serien?bereich=persoenlich" aria-label="Eigene Serie bearbeiten">↗</Link> : null}</div>) : <EmptyState>Noch keine geteilten Serien vorhanden.</EmptyState>}</div><p className="muted">Die Freigabe einer Serie gilt für neue Buchungen. Bereits erfasste Ausgaben behalten ihre eigene Freigabe.</p></section> : null}
    {section === "sicherung" ? <><h2>Familienexport</h2><p>Enthält ausschließlich geteilte Ausgaben mit gemeinsamen Begriffen und zahlender Person. Die Datei dient zur Auswertung. Wiederherstellung erfolgt aus persönlichen Sicherungen oder dem Datenbankbackup.</p><form action="/api/expenses/export" className="form-grid"><input type="hidden" name="bereich" value="familie"/><label>Jahr<input name="year" type="number" min={1900} max={2100} defaultValue={new Date().getFullYear()}/></label><button className="button">Excel herunterladen</button></form><form action={exportFamilyFinanceToSynology} className="form-grid"><label>Jahr<input name="year" type="number" min={1900} max={2100} defaultValue={new Date().getFullYear()}/></label><button className="button secondary">Auf Synology exportieren</button></form></>:null}
  </div>;
}
